#!/usr/bin/env python3
"""Dev tool: a readable copy of the converted add-on, for browsing.

Copies the Bedrock definitions the converter carried over (dev/converted:
client entities, attachables, render and animation controllers, animations,
behavior entities, trade tables) into dev/readable, with the add-on's ids
swapped for the mod's readable names (src/main/resources/villagernewsjavafied/
names): characters, items, properties, script events, the dialogs the behavior
pack asks for, Molang variables and bones. Files are renamed after what they
define (entity/ebp.json -> entity/villager.json). Also writes
dev/readable/INDEX.md: every name and the id it stands for.

The copy is for reading only: nothing loads it, and like everything in dev/
it is never committed.

Usage: python3 tools/readable_pack.py
"""
import json
import pathlib
import re
import shutil

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONVERTED = ROOT / "dev/converted"
OUT = ROOT / "dev/readable"
NAMES_DIR = ROOT / "src/main/resources/villagernewsjavafied/names"
NAMESPACE = "oreville_vn"


def load_names():
    manifest = json.loads((CONVERTED / "manifest.json").read_text())
    versions = json.loads((NAMES_DIR / "index.json").read_text())["versions"]
    version = manifest.get("addonVersion")
    chosen = version if version in versions else versions[-1]
    return version, json.loads((NAMES_DIR / f"villager_news-{chosen}.json").read_text())


def build_rewriter(names, dialog_names):
    def inverse(section):
        return {v: k for k, v in names.get(section, {}).items()}

    namespaced = {}
    for section in ("characters", "entities", "items"):
        namespaced.update(inverse(section))
    events = {v.split(":", 1)[1]: k for k, v in names.get("script_events", {}).items()}
    properties = {v[2:]: k for k, v in names.get("properties", {}).items()}
    variables = inverse("variables")
    bones = inverse("bones")

    def rewrite(text):
        text = re.sub(r"(scriptevent " + NAMESPACE + r":)(\w+) (\w+)",
                      lambda m: m.group(1) + events.get(m.group(2), m.group(2)) + " " + dialog_names.get(m.group(3), m.group(3)), text)
        text = re.sub(NAMESPACE + r":(\w+)", lambda m: NAMESPACE + ":" + namespaced.get(m.group(1), m.group(1)), text)
        text = re.sub(r"p:(\w+)", lambda m: "p:" + properties.get(m.group(1), m.group(1)), text)
        text = re.sub(r"\b(v|variable)\.(\w+)", lambda m: m.group(1) + "." + variables.get(m.group(2), m.group(2)), text)
        text = re.sub(r'"(\w+)"', lambda m: '"' + bones.get(m.group(1), m.group(1)) + '"', text)
        return text

    return rewrite


def readable_file_name(path, text, rewrite):
    """Client entities, attachables and behavior entities are named after their identifier."""
    try:
        data = json.loads(text)
    except ValueError:
        return path.name
    for key in ("minecraft:client_entity", "minecraft:attachable", "minecraft:entity"):
        description = data.get(key, {}).get("description", {}) if isinstance(data, dict) else {}
        identifier = description.get("identifier")
        if identifier:
            return rewrite(identifier).split(":", 1)[-1] + path.suffix
    return path.name


def main():
    version, names = load_names()
    dialogs = json.loads((CONVERTED / "server/dialogs.json").read_text())["dialogs"]
    dialog_names = {d["id"]: name for name, d in dialogs.items()}
    rewrite = build_rewriter(names, dialog_names)

    if OUT.exists():
        shutil.rmtree(OUT)
    sources = [CONVERTED / "assets/villagernewsjavafied/bedrock", CONVERTED / "server/entities", CONVERTED / "server/trading"]
    count = 0
    for source in sources:
        if not source.is_dir():
            continue
        for path in sorted(source.rglob("*")):
            if not path.is_file() or path.suffix not in (".json", ".material"):
                continue
            text = rewrite(path.read_text(encoding="utf-8"))
            relative = path.relative_to(source).parent
            target = OUT / source.name / relative / readable_file_name(path, path.read_text(encoding="utf-8"), rewrite)
            if target.exists():
                target = target.with_name(target.stem + "_" + path.stem + target.suffix)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8")
            count += 1

    lines = [f"# Readable names (add-on {version})", "",
             "Local copy for browsing; generated by tools/readable_pack.py, never committed.", ""]
    for section, table in names.items():
        if isinstance(table, dict) and section != "dialogs":
            lines += [f"## {section}", "", "| name | add-on id |", "|---|---|"]
            lines += [f"| `{name}` | `{addon_id}` |" for name, addon_id in sorted(table.items())]
            lines.append("")
    lines += ["## dialogs", "", "| name | add-on id | lines |", "|---|---|---|"]
    lines += [f"| `{name}` | `{d['id']}` | {len(d['lines'])} |" for name, d in sorted(dialogs.items())]
    (OUT / "INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{count} files -> {OUT.relative_to(ROOT)} (see INDEX.md)")


if __name__ == "__main__":
    main()
